name: ci

on:
  push:
    tags:
      - 'v*'        # runs on tags like v1.0.0, v2.3.4
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            ninja-build \
            g++ \
            libqpdf-dev \
            libxkbcommon-dev \
            qpdf \
            poppler-utils \
            qt6-base-dev \
            qt6-tools-dev \
            qt6-tools-dev-tools

      - name: Debug Qt installation
        run: |
          find /usr -name Qt6Config.cmake -o -name qt6-config.cmake

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
